//! Core traits implemented by `#[derive(Choice)]`, `#[derive(Score)]`, and `#[derive(Questions)]`.

use serde_json::Value;

use crate::answer::AnswerMeta;
use crate::decode::DecodeError;
use crate::wire::{Entry, Question, WireQuestions, WireResponse};

/// Inclusive upper bound on Choice variants (TypeSafe launch bound).
pub const MAX_CHOICE_OPTIONS: usize = 255;
/// Inclusive lower bound on Choice variants.
pub const MIN_CHOICE_OPTIONS: usize = 2;
/// Inclusive lower bound on Score levels.
pub const MIN_SCORE_LEVELS: usize = 2;

/// Question instructions: a string or JSON object/array, stored as `'static` data.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Instructions {
    /// Plain-text instructions.
    Text(&'static str),
    /// JSON text parsed when building the wire question (validated by the derive).
    Json(&'static str),
}

impl Instructions {
    /// Convert to a wire [`Entry`].
    pub fn to_entry(self) -> Entry {
        match self {
            Instructions::Text(s) => Entry::from(s),
            Instructions::Json(raw) => match serde_json::from_str::<Value>(raw) {
                Ok(v) => Entry::from(v),
                Err(_) => Entry::from(raw),
            },
        }
    }
}

/// A criteria description: string, JSON, or null.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Description {
    /// Plain-text description.
    Text(&'static str),
    /// JSON text parsed when building the wire question (validated by the derive).
    Json(&'static str),
    /// Explicit null (empty description).
    Null,
}

impl Description {
    /// Convert to a wire [`Entry`].
    pub fn to_entry(self) -> Entry {
        match self {
            Description::Text(s) => Entry::from(s),
            Description::Json(raw) => match serde_json::from_str::<Value>(raw) {
                Ok(v) => Entry::from(v),
                Err(_) => Entry::from(raw),
            },
            Description::Null => Entry::Null,
        }
    }
}

/// A type that maps to one System One Choice question.
pub trait ChoiceQuestion: Sized + Copy + Eq + 'static {
    /// Instructions sent as the Choice `instructions` field.
    const INSTRUCTIONS: Instructions;
    /// Variants in declaration order.
    const VARIANTS: &'static [Self];
    /// Wire label (stable, snake_case by default).
    fn label(self) -> &'static str;
    /// Criteria description for this variant.
    fn description(self) -> Description;
    /// Inverse of [`Self::label`].
    fn from_label(label: &str) -> Option<Self>;
    /// Zero-based index in [`Self::VARIANTS`].
    fn index(self) -> usize;
}

/// Ordered score levels. Declaration order is the wire order of `criteria`.
pub trait ScoreQuestion: Sized + Copy + Eq + Ord + 'static {
    /// Instructions sent as the Score `instructions` field.
    const INSTRUCTIONS: Instructions;
    /// Levels in declaration order (index 0..n-1).
    const LEVELS: &'static [Self];
    /// Criteria description for this level.
    fn level_description(self) -> Description;
    /// Zero-based index in [`Self::LEVELS`].
    fn index(self) -> usize;
    /// Inverse of [`Self::index`].
    fn from_index(i: usize) -> Option<Self>;
}

/// A field type that becomes one question in a [`QuestionSet`].
///
/// Implemented by `#[derive(Choice)]` and `#[derive(Score)]`.
pub trait QuestionField: Sized {
    /// Typed answer stored on the generated answers struct.
    type Answer;
    /// Wire question for this field.
    fn wire_question() -> Question;
    /// Decode this field from a response.
    fn decode_field(
        key: &str,
        resp: &WireResponse,
        meta: &mut AnswerMeta,
    ) -> Result<Self::Answer, DecodeError>;

    /// Decode an optional field: missing key yields `Ok(None)`.
    fn decode_optional(
        key: &str,
        resp: &WireResponse,
        meta: &mut AnswerMeta,
    ) -> Result<Option<Self::Answer>, DecodeError> {
        if resp.answers.contains_key(key) {
            Self::decode_field(key, resp, meta).map(Some)
        } else {
            Ok(None)
        }
    }
}

/// A struct whose fields are questions. Generated by `#[derive(Questions)]`.
pub trait QuestionSet: Sized {
    /// Generated struct of typed answers (plus [`AnswerMeta`]).
    type Answers;
    /// Wire questions map. State is filled by the caller of [`crate::S1::ask`].
    fn questions() -> WireQuestions;
    /// Decode a full response into [`Self::Answers`].
    fn decode(resp: &WireResponse) -> Result<Self::Answers, DecodeError>;
}
